---------------------------------------------------------------------------
---------------------------------------------------------------------------
---	Universidade Federal de São Carlos - Campus Sorocaba 		---
---	Bacharelado em Ciência da Computação				---
---	Sorriso de Criança						---
---									---
---		Bruno Pereira						---
---		Celso Araujo Filho					---
---		Cristiano Silva						---
---		Pedro Brito Junior					---
---		Yasmin Beatriz Alves da Silva 				---
---									---
---------------------------------------------------------------------------
---------------------------------------------------------------------------

--criação do banco

--CREATE DATABASE SorrisoDeCrianca;

CREATE TABLE LOGIN 
(
	USUARIO VARCHAR(20) PRIMARY KEY,
	SENHA VARCHAR(20) NOT NULL,
	PRIVILEGIO VARCHAR(5) NOT NULL CHECK (PRIVILEGIO IN ('admin', 'comum'))
);

CREATE TABLE CRIANCA
(
	ID NUMERIC PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	RG VARCHAR(9) NOT NULL,
	SEXO VARCHAR (9) NOT NULL CHECK (SEXO IN ('Masculino', 'Feminino')),
	STATUS VARCHAR (7) NOT NULL CHECK (STATUS IN ('Ativo', 'Inativo')),
	ENDERECO VARCHAR(200),
	NOME_RESPONSAVEL VARCHAR(100),
	TEL_CONTATO VARCHAR(11),
	OBSERVACAO VARCHAR(300),
	--Sobre a casa
	LUZ_ELETRICA VARCHAR(2) CHECK (LUZ_ELETRICA IN ('S', 'N')),
	AGUA_ENCANADA VARCHAR(2) CHECK (AGUA_ENCANADA IN ('S', 'N')),
	ESGOTO VARCHAR(2) CHECK (ESGOTO IN ('S', 'N')),
	--Condicao da crianca
	CONVENIO_MEDICO VARCHAR(30),
	CENTRO_SAUDE VARCHAR(30),
	SARAMPO VARCHAR(2) CHECK (SARAMPO IN ('S', 'N')),
	RUBEOLA VARCHAR(2) CHECK (RUBEOLA IN ('S', 'N')),
	BRONCO_PNEUMONIA VARCHAR(2) CHECK (BRONCO_PNEUMONIA IN ('S', 'N')),
	CATAPORA VARCHAR(2) CHECK (CATAPORA IN ('S', 'N')),
	CONQUELUCHE VARCHAR(2) CHECK (CONQUELUCHE IN ('S', 'N')),
	HEPATITE VARCHAR(2) CHECK (HEPATITE IN ('S', 'N')),
	MENINGITE VARCHAR(2) CHECK (MENINGITE IN ('S', 'N')),
	CONVULSAO VARCHAR(2) CHECK (CONVULSAO IN ('S', 'N')),
	PROBLEMAS_RESPIRATORIOS VARCHAR(2) CHECK (PROBLEMAS_RESPIRATORIOS IN ('S', 'N')),
	ALERGIA VARCHAR(2) CHECK (ALERGIA IN ('S', 'N')),
	JA_FOI_INTERNADA VARCHAR(2) CHECK (JA_FOI_INTERNADA IN ('S', 'N')),
	DIARREIA_FREQUENTE VARCHAR(2) CHECK (DIARREIA_FREQUENTE IN ('S', 'N')),
	DIABETES VARCHAR(2) CHECK (DIABETES IN ('S', 'N')),
	USA_INSULINA VARCHAR(2) CHECK (USA_INSULINA IN ('S', 'N')),
	OUTRAS_DOENCAS VARCHAR(30),
	MEDICAMENTOS_ALERGICOS VARCHAR(30),
	PODE_SAIR_SOZINHA VARCHAR(2) CHECK (PODE_SAIR_SOZINHA IN ('S', 'N')),
	
);

CREATE TABLE INTERESSADO
(
	ID NUMERIC PRIMARY KEY AUTO_INCREMENT,
	NOME_CRIANCA VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ENDERECO VARCHAR(200),
	NOME_RESPONSAVEL VARCHAR(100),
	TEL_CONTATO VARCHAR(11),
	OBSERVACAO VARCHAR(300)
);

CREATE TABLE VOLUNTARIO
(
	ID NUMERIC PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	RG VARCHAR(9) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SEXO VARCHAR (9) NOT NULL CHECK (SEXO IN ('Masculino', 'Feminino')),
	SITUACAO_PROFISSIONAL VARCHAR (11) NOT NULL CHECK (SITUACAO_PROFISSIONAL IN ('Aposentado', 'Empregado', 'Autônomo', 'Estudante', 'Do Lar')),
	FORMACAO VARCHAR (9) NOT NULL CHECK (FORMACAO IN ('1ºGrau', '2ºGrau', 'Superior')),
	OCUPACAO VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(200),
	TEL_CONTATO VARCHAR(11),
	EMAIL VARCHAR(20),
	DIAS_SEMANA VARCHAR (50) NOT NULL,
	PERIODO VARCHAR (6) NOT NULL CHECK (PERIODO IN ('Manhã', 'Tarde')),
	OBSERVACAO VARCHAR(300)
);

CREATE TABLE PRESENCA
(
	CRIANCA NUMERIC NOT NULL,
	DATA_PRESENCA DATE NOT NULL,
	STATUS VARCHAR (1) NOT NULL CHECK (STATUS IN ('P', 'F')),
	CONSTRAINT FK_CRIANCA FOREIGN KEY (CRIANCA) REFERENCES CRIANCA(ID),
	CONSTRAINT PK_PRESENCA PRIMARY KEY (CRIANCA,DATA_PRESENCA)	
);

-- população para teste

INSERT INTO LOGIN VALUES('admin', 'sysadmin', 'admin');
INSERT INTO LOGIN VALUES('professor', 'professor', 'comum'); 

INSERT INTO CRIANCA (NOME, DATA_NASCIMENTO, RG, SEXO, STATUS, ENDERECO, NOME_RESPONSAVEL, TEL_CONTATO, OBSERVACAO) VALUES('João Paulo', '2008-12-10', '911225341', 'Masculino', 'Ativo', 'Rua 20 de Janeiro, n80', 'Paula Paulo','1598966548', '');
INSERT INTO CRIANCA (NOME, DATA_NASCIMENTO, RG, SEXO, STATUS, ENDERECO, NOME_RESPONSAVEL, TEL_CONTATO, OBSERVACAO) VALUES('Maria Clara', '2007-11-08', '418757896', 'Feminino', 'Ativo', 'Rua 20 de Janeiro, n127', 'Maria Souza','1598276598', '');

INSERT INTO VOLUNTARIO VALUES(0,'Jaqueline Silva', '1990-06-08', '429434121', '42603235800', 'Feminino', 'Professora', 'Av Principal n1187', '1599874561', 'email@email.com', '');

INSERT INTO PRESENCA VALUES(1,'2016-09-14','P');
INSERT INTO PRESENCA VALUES(1,'2016-09-15','F');
INSERT INTO PRESENCA VALUES(1,'2016-09-16','P');
INSERT INTO PRESENCA VALUES(2,'2016-09-14','P');
INSERT INTO PRESENCA VALUES(2,'2016-09-15','P');
INSERT INTO PRESENCA VALUES(2,'2016-09-16','F');

-- criação do usuário do banco

/* CREATE USER sistemasorrisodecrianca WITH PASSWORD 'syssdc';
GRANT SELECT ON LOGIN TO sistemasorrisodecrianca;
GRANT SELECT, INSERT, UPDATE ON CRIANCA TO sistemasorrisodecrianca;
GRANT SELECT, INSERT, UPDATE ON VOLUNTARIO TO sistemasorrisodecrianca;
GRANT SELECT, INSERT ON PRESENCA TO sistemasorrisodecrianca; */

-- h2 cipher user and password

/*user
34z474kw94owc0m4g0trw4xs7ksmbkpc2mtc
senha
57cbggmymby8e2zbpcvu9c742zfke8kqpkw0 ya7xmo23j18gjut1q8az61hcsqg1z46jcjcw */
